#!/bin/bash
# On OSX install with:
#   sudo defaults write com.apple.loginwindow LogoutHook $HOME/.homesick/repos/dotfiles/suspend_virtualboxes
current_user=$(whoami)
user='khs'
if [[ $current_user != $user ]]; then
	sudo="sudo -u $user"
fi
for uuid in $($sudo VBoxManage list runningvms | awk '{print $NF}'); do
	$sudo VBoxManage controlvm ${uuid} savestate
done
